name: Docker Build and Publish

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Packages
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      
    - name: Convert repository name to lowercase
      run: echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]' > repo_name.txt

    - name: Build Docker image
      run: cat repo_name.txt | xargs -I {} docker build -t docker.pkg.github.com/${{ github.repository }}/gaia_project_fe:latest .

    - name: Push Docker image to GitHub Packages
      run: |
        cat repo_name.txt | xargs -I {} docker tag docker.pkg.github.com/${{ github.repository }}/gaia_project_fe:latest docker.pkg.github.com/{}/gaia_project_fe:latest
        cat repo_name.txt | xargs -I {} docker push docker.pkg.github.com/{}/gaia_project_fe:latest
